In [1]:
# 라이브러리 import
import pandas as pd
import tensorflow as tf


In [2]:
# data 불러오기
Iris = pd.read_csv("/content/iris.csv")
Iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
# 원핫 인코딩
encoded_Iris = pd.get_dummies(Iris)
encoded_Iris

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0     5.1  3.5    1.4   0.2          1              0             0
1     4.9  3.0    1.4   0.2          1              0             0
2     4.7  3.2    1.3   0.2          1              0             0
3     4.6  3.1    1.5   0.2          1              0             0
4     5.0  3.6    1.4   0.2          1              0             0
..    ...  ...    ...   ...        ...            ...           ...
145   6.7  3.0    5.2   2.3          0              0             1
146   6.3  2.5    5.0   1.9          0              0             1
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

[150 rows x 7 columns]

In [4]:
encoded_Iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   꽃잎길이           150 non-null    float64
 1   꽃잎폭            150 non-null    float64
 2   꽃받침길이          150 non-null    float64
 3   꽃받침폭           150 non-null    float64
 4   품종_setosa      150 non-null    uint8  
 5   품종_versicolor  150 non-null    uint8  
 6   품종_virginica   150 non-null    uint8  
dtypes: float64(4), uint8(3)
memory usage: 5.3 KB


In [5]:
encoded_Iris.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [6]:
# 독립변수, 종속변수 분리하기

독립 = encoded_Iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = encoded_Iris[['품종_setosa', '품종_versicolor', '품종_virginica']]

In [7]:
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [16]:
# 모델 생성
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(5, activation='swish')(X)
H = tf.keras.layers.Dense(5, activation='swish')(H)
H = tf.keras.layers.Dense(5, activation='swish')(H)
y = tf.keras.layers.Dense(3, activation='softmax')(H)

model = tf.keras.models.Model(X, y)
model.compile(loss="categorical_crossentropy",
              metrics='accuracy')

In [17]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 25        
_________________________________________________________________
dense_3 (Dense)              (None, 5)                 30        
_________________________________________________________________
dense_4 (Dense)              (None, 5)                 30        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 18        
Total params: 103
Trainable params: 103
Non-trainable params: 0
_________________________________________________________________


In [18]:
# 모델 학습
model.fit(독립, 종속, epochs=600, verbose=0)
model.fit(독립, 종속, epochs=10)
# 학습이 되고있는지를 확인해 보는 척도는 accuracy보단 loss를 확인할 것

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0514 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0492 - accuracy: 0.9867
Epoch 3/10
5/5 [==============================] - 0s 5ms/step - loss: 0.0468 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0502 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0496 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0463 - accuracy: 0.9867
Epoch 7/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0456 - accuracy: 0.9867
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0462 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0453 - accuracy: 0.9867
Epoch 10/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0505 - accuracy: 0.9867


In [24]:
# 모델 예측

model.predict(독립[:10])
# 5번째 인덱스까지 확인했을 때, 
# 첫번째 컬럼인 품종_setosa를 9.8이상으로 예측, 두번째, 3번째 컬럼은 1에 가깝게 예측을 함 

array([[1.0000000e+00, 5.5948114e-08, 8.4458387e-09],
       [9.9999964e-01, 3.7108754e-07, 3.7808029e-08],
       [9.9999976e-01, 2.6308305e-07, 3.0012508e-08],
       [9.9999881e-01, 1.1107965e-06, 7.0065440e-08],
       [9.9999988e-01, 5.9644329e-08, 8.5834566e-09],
       [9.9999988e-01, 1.2005600e-07, 8.6156211e-09],
       [9.9999928e-01, 6.5732132e-07, 4.3571657e-08],
       [9.9999988e-01, 1.4673797e-07, 1.5744931e-08],
       [9.9999762e-01, 2.2806867e-06, 1.3548292e-07],
       [9.9999976e-01, 2.1735804e-07, 2.5997549e-08]], dtype=float32)

In [25]:
종속[:10]

# 실제로 5번째 인덱스까지 데이터는 setosa 였음

품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
5          1              0             0
6          1              0             0
7          1              0             0
8          1              0             0
9          1              0             0

In [26]:
# 학습한 가중치 출력

model.get_weights()

[array([[-0.15318576,  0.5156754 ,  0.5838406 ,  0.6106842 ,  0.8609073 ],
        [-0.41420916, -0.58380103,  0.64094895,  0.18201303, -0.3971535 ],
        [-0.0543223 ,  0.5354823 ,  0.0301136 , -0.5053925 , -0.54112893],
        [ 0.17954893,  1.000252  ,  0.00592977, -0.69779366, -0.854525  ]],
       dtype=float32),
 array([-0.09824269, -0.26117066,  0.34519196,  0.26130462,  0.32148147],
       dtype=float32),
 array([[-0.45169127, -1.2325844 ,  0.24678366, -0.3701212 , -0.5345298 ],
        [ 0.91271514, -0.09710382, -0.5626757 , -0.5494499 , -0.28885084],
        [-0.05159466, -0.47815582, -0.05491711,  0.55355173, -0.30989456],
        [-0.3126654 ,  0.09317328,  1.1829087 ,  0.4533398 , -0.07364329],
        [-0.38641828,  0.5358729 ,  0.12366274,  0.47618338, -0.24741217]],
       dtype=float32),
 array([0.18778643, 0.4069213 , 0.12292049, 0.44910797, 0.4567076 ],
       dtype=float32),
 array([[-0.13116062,  0.6217082 ,  1.0483785 , -0.9178111 , -0.03974318],
        [-1.5